---
# Defines deployment design and assigns role to server groups

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  sudo: True
  roles:
  - common

- hosts: mons
  sudo: True
  roles:
  - mon

- hosts: osds
  sudo: True
  roles:
  - osd

- hosts: mdss
  sudo: True
  roles:
  - mds

- hosts: rgws
  sudo: True
  roles:
  - radosgw
