---
# Defines deployment design and assigns role to server groups

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  sudo: True
  roles:
  - { role: ceph-common, when: not docker }

- hosts: mons
  sudo: True
  roles:
  - ceph-mon

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw
