---
# Defines deployment design and assigns role to server groups

- hosts: mons
  sudo: True
  roles:
  - ceph-mon
  - ceph-restapi

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw
