---
- name: create nfs gateway directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "ceph"
    group: "ceph"
    mode: "0755"
  with_items:
    - /var/lib/nfs/ganesha
    - /var/run/ganesha

- name: generate ganesha configuration file
  action: config_template
  args:
    src: "{{ playbook_dir }}/roles/ceph-common/templates/ganesha.conf.j2"
    dest: /etc/ganesha/ganesha.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ ganesha_conf_overrides }}"
    config_type: ini

- name: start nfs gateway service
  service:
    name: nfs-ganesha
    state: started
    enabled: yes
