---
- name: Disable OSD directory parsing by updatedb
  command: updatedb -e /var/lib/ceph
  ignore_errors: true

- name: Increase PID max value to a very large value
  sysctl: >
    name="kernel.pid_max"
    value={{ os_tuning_pid_max }}
    state=present
    sysctl_file=/etc/sysctl.conf

- name:  Increase the maximum number of open files
  sysctl: >
    name="fs.file-max"
    value={{ os_tuning_file_max }}
    state=present
    sysctl_file=/etc/sysctl.conf
