---
- name: Disable OSD directory parsing by updatedb
  command: updatedb -e /var/lib/ceph
  ignore_errors: true

- name: Disable transparent hugepage
  command: "echo never > /sys/kernel/mm/redhat_transparent_hugepage/enabled"
  ignore_errors: true
  when: disable_transparent_hugepage

- name: Apply OS tuning
  sysctl: >
    name={{ item.name }}
    value={{ item.value }}
    state=present
    sysctl_file=/etc/sysctl.conf
  with_items: os_tuning_params
