---
- name: Disable OSD directory parsing by updatedb
  command: updatedb -e /var/lib/ceph
  ignore_errors: true

- name: Apply OS tuning
  sysctl: >
    name={{ item.name }}
    value={{ item.value }}
    state=present
    sysctl_file=/etc/sysctl.conf
  with_items: os_tuning_params
