---
- name: determine if node is registered with subscription-manager.
  command: subscription-manager identity
  register: subscription
  changed_when: false

- name: enable red hat storage monitor repository
  command: subscription-manager repos --enable rhel-7-server-rhceph-1.3-mon-rpms
  when: mon_group_name in group_names

- name: enable red hat storage osd repository
  command: subscription-manager repos --enable rhel-7-server-rhceph-1.3-osd-rpms
  when: osd_group_name in group_names

- name: enable red hat storage rados gateway repository
  command: subscription-manager repos --enable rhel-7-server-rhceph-1.3-tools-rpms
  when: rgw_group_name in group_names
