---

- name: "update apt cache"
  action: apt update-cache=yes

- name: "restart ceph ubuntu"
  shell: service ceph restart ; service ceph-osd-all restart
  when: socket.rc == 0

- name: "restart ceph debian redhat"
  command: service ceph restart
  when: socket.rc == 0
