---
- name: generate systemd unit file
  become: true
  template:
    src: "{{ role_path }}/templates/ceph-mds.service.j2"
    dest: /etc/systemd/system/ceph-mds@.service
    owner: "root"
    group: "root"
    mode: "0644"

- name: systemd start mds container
  systemd:
    name: ceph-mds@{{ ansible_hostname }}
    state: started
    enabled: yes
    daemon_reload: yes
  changed_when: false
