---
- name: create ganesha conf directory
  file:
    path: /etc/ganesha
    state: directory
    owner: root
    group: root
    mode: 0644

- name: get user create output
  command: docker logs ceph-rgw-user-{{ ansible_hostname }}
  always_run: true
  register: rgwuser

- name: generate ganesha configuration file
  action: config_template
  args:
    src: "{{ playbook_dir }}/roles/ceph-common/templates/ganesha.conf.j2"
    dest: /etc/ganesha/ganesha.conf
    owner: "root"
    group: "root"
    mode: "0644"
    config_overrides: "{{ ganesha_conf_overrides }}"
    config_type: ini
