---
- name: include copy_configs.yml
  include: copy_configs.yml

- name: copy_ganesha_configs.yml
  include: copy_ganesha_configs.yml
  when: not containerized_deployment_with_kv

- name: start_docker_nfs.yml
  include: start_docker_nfs.yml

