---
- name: Create RGW directory
  file: >
    path=/var/lib/ceph/radosgw/ceph-radosgw.{{ ansible_fqdn }}
    state=directory
    owner=root
    group=root
    mode=0644

- name: Copy RGW bootstrap key
  copy: >
    src=fetch/{{ fsid }}/etc/ceph/ceph.client.radosgw.{{ ansible_hostname }}.keyring
    dest=/var/lib/ceph/radosgw/ceph-radosgw.{{ ansible_hostname }}/keyring
    owner=root
    group=root
    mode=600
  when: cephx

- name: Activate RGW with upstart
  file: >
    path=/var/lib/ceph/radosgw/ceph-radosgw.{{ ansible_fqdn }}/done
    state=touch
    owner=root
    group=root
    mode=0644
